# to create an env from this file run: $ conda env create -f environment.yml
# to update your current env run: $ conda env update --file mnist_environment.yml  --prune

name: mnist
channels:
  - defaults
dependencies:
  - jupyterlab
  - matplotlib
  - numpy
  - pandas=1.3
  - python=3.8
  - scikit-learn
